services:
  omarchy:
    build: .
    environment:
      - RAILS_ENV=production
      - PORT=3000
      - SERVICE_FQDN_OMARCHY_3000
      - DATABASE_URL=${SERVICE_URL_POSTGRES}
      - SECRET_KEY_BASE=${SERVICE_PASSWORD_SECRET_KEY}
      - ADMIN_PASSWORD=${SERVICE_PASSWORD_ADMIN}
      - APP_HOST=${SERVICE_FQDN_OMARCHY}
    volumes:
      - app_data:/app/tmp
      - app_logs:/app/log
