services:
  omarchy:
    image: howieduhzit/omarchy-apps:latest
    environment:
      - RAILS_ENV=production
      - PORT=3000
      - SERVICE_FQDN_OMARCHY_3000
      - DATABASE_URL=${SERVICE_URL_POSTGRES}
      - SECRET_KEY_BASE=${SERVICE_PASSWORD_SECRET_KEY}
      - ADMIN_PASSWORD=${SERVICE_PASSWORD_ADMIN}
      - APP_HOST=${SERVICE_FQDN_OMARCHY}
    volumes:
      - app_data:/app/tmp
      - app_logs:/app/log
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=omarchy_directory_production
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${SERVICE_PASSWORD_POSTGRES}
    volumes:
      - postgres_data:/var/lib/postgresql/data
