services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
      target: development
    environment:
      RAILS_ENV: development
    volumes:
      - ./:/app
      - bundle:/bundle
      - ./db:/app/db
    ports:
      - "3000:3000"
    command: ["bin/rails", "server", "-b", "0.0.0.0"]

volumes:
  bundle:
