services:
  omarchy:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "3001:3000"
    environment:
      - RAILS_ENV=production
      - SECRET_KEY_BASE=test_secret_key_base_for_local_testing_only
      - ADMIN_PASSWORD=admin123
      - APP_HOST=localhost
    volumes:
      - ./db:/app/db
      - ./log:/app/log

volumes:
