services:
  omarchy:
    image: howieduhzit/omarchy-apps:latest
    environment:
      - RAILS_ENV=production
      - PORT=3000
      - SERVICE_FQDN_OMARCHY_3000
      - SECRET_KEY_BASE=${SERVICE_PASSWORD_SECRET_KEY}
      - ADMIN_PASSWORD=${SERVICE_PASSWORD_ADMIN}
      - APP_HOST=${SERVICE_FQDN_OMARCHY}
      - RAILS_SERVE_STATIC_FILES=true
      - RAILS_LOG_TO_STDOUT=true
      - RAILS_LOG_LEVEL=info
      - RAILS_FORCE_SSL=false
    volumes:
      - app_data:/app/db
      - app_logs:/app/log
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  app_data:
  app_logs:
