services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: omarchy
      POSTGRES_PASSWORD: omarchy
      POSTGRES_DB: omarchy_directory_development
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U omarchy -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  web:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      RAILS_ENV: development
      PGHOST: db
      PGPORT: 5432
      PGUSER: omarchy
      PGPASSWORD: omarchy
      PGDATABASE: omarchy_directory_development
    volumes:
      - ./:/app
      - bundle:/bundle
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    command: ["bin/rails", "server", "-b", "0.0.0.0"]

volumes:
  pgdata:
  bundle:
