[variables]
NODE_ENV = "production"
RAILS_ENV = "production"

[phases.setup]
nixPkgs = ["sqlite"]

[phases.install]
cmds = [
  "bundle config set --local deployment 'true'",
  "bundle config set --local without 'development test'",
  "bundle install"
]

[phases.build]
cmds = [
  "bundle exec rails assets:precompile",
  "bundle exec rails db:migrate",
  "bundle exec rails db:seed"
]

[start]
cmd = "bundle exec rails server -b 0.0.0.0 -p 3000"
