[variables]
NODE_ENV = "production"
RAILS_ENV = "production"
DATABASE_URL = "sqlite3:db/production.sqlite3"
SECRET_KEY_BASE = "your_secret_key_base_here_change_this_in_production"

[phases.setup]
nixPkgs = ["sqlite"]

[phases.install]
cmds = [
  "bundle config set --local deployment 'true'",
  "bundle config set --local without 'development test'",
  "bundle install"
]

[phases.build]
cmds = [
  "mkdir -p db",
  "chmod 755 db",
  "mkdir -p app/assets/builds",
  "chmod 755 app/assets/builds",
  "mkdir -p public/assets",
  "chmod 755 public/assets",
  "echo 'Setting up database...'",
  "bundle exec rails db:create",
  "bundle exec rails db:migrate",
  "bundle exec rails db:seed",
  "bundle exec rails assets:precompile"
]

[start]
cmd = "bundle exec rails server -b 0.0.0.0 -p 3000"
